# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.4
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm run build
      - run: git config --global user.name "Xunk-Bot" && git config --global user.email "xunk@radialapps.com" && git config --global push.default matching
      - run: git clone git@github.com:go-xunk/xunk-calendar-demo.git goxunk
      - run: cd goxunk && rm -r * && cp -R ../dist/* ./ && sed -i 's#<base href="/">#<base href="/xunk-calendar-demo/">#g' index.html && git add -A && git commit -m "Automated Build" && git push && cd ..
      - run: npm run packagr
      - run: npm run lint